/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LOGIN;

import COMMONFUN.DefaultData;
import CONTROLLERS.C_UserGroup;
import CONTROLLERS.C_Users;
import GLOBALDATA.GlobalData;
import MAIN.Frm_Main;
import MODELS.MPermissions;
import MODELS.MUser;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;

/**
 *
 * @author HOME
 */
public class Frm_Login extends javax.swing.JFrame {

    C_Users u = null;
    C_UserGroup ug = null;
    DefaultData def = null;
    Frm_Login frml = null;

    public Frm_Login() {
        initComponents();
        def = new DefaultData();

        createLayout();

        u = new C_Users();
        ug = new C_UserGroup();
        txtuname.grabFocus();
        this.frml = this;
        this.lbl_ComName.setText(GlobalData.Setup.getComname());
        this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        this.setBounds(this.getX(), this.getY(), 590, 340);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        butLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        lbl_ComName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl_ComLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butLogin.setForeground(new java.awt.Color(102, 102, 102));
        butLogin.setText("Login");
        butLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        butLogin.setContentAreaFilled(false);
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });
        jPanel1.add(butLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 90, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 60, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 70, 30));

        txtuname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtuname.setForeground(new java.awt.Color(102, 102, 102));
        txtuname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        jPanel1.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 170, 30));

        txtpass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtpass.setForeground(new java.awt.Color(102, 102, 102));
        txtpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Software By :  Buwaneka  Sumanasekara");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 590, 20));

        lbl_ComName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ComName.setForeground(new java.awt.Color(102, 102, 102));
        lbl_ComName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ComName.setText("COMNAME");
        jPanel1.add(lbl_ComName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 40, 40));
        jPanel1.add(lbl_ComLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        login();

    }//GEN-LAST:event_butLoginActionPerformed

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        txtpass.grabFocus();
    }//GEN-LAST:event_txtunameActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        login();
    }//GEN-LAST:event_txtpassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clear() {
        txtuname.setText("");
        txtpass.setText("");
        txtuname.grabFocus();
    }

    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

            // UIManager.setLookAndFeel("com.jtattoo.plaf." + CommonFun.getSystemTheme());
        } catch (Exception ex) {
            Logger.getLogger(Frm_Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ComLogo;
    private javax.swing.JLabel lbl_ComName;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables

    private void login() {

        if (txtuname.getText().equals("") || txtpass.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please Fill the fileds", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                MUser user = u.CheckUserLogin(txtuname.getText(), txtpass.getText());
                if (user != null) {
                    this.dispose();

                    ArrayList<MPermissions> Menus = ug.getUserGroupPermitions(user.getMUsergroup().getId(), 1);
                    Map<String, MPermissions> SpecialPer = ug.getUserGroupPermitions_Map(user.getMUsergroup().getId(), 2, "");
                    GlobalData.SpecialPer = SpecialPer;
                    GlobalData.CurUser = user;
                    final Frm_Main frm = new Frm_Main(this, Menus);
                    frm.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Login faild,Please try again", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);

                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }

    }

    private void createLayout() {
        //  def.createDefaultData();
        File f = new File("MyData\\Company\\" + GlobalData.Setup.getComimg());
       // System.out.println(f.getAbsolutePath());
        if (f.exists()) {
            BufferedImage img = null;
            try {
                img = ImageIO.read(f);
                Image dimg = img.getScaledInstance(260, 170,
                        Image.SCALE_AREA_AVERAGING);

                lbl_ComLogo.setIcon(new ImageIcon(dimg));
                lbl_ComLogo.setHorizontalAlignment(SwingConstants.CENTER);
            } catch (IOException e) {
                e.printStackTrace();
            }

        } else {
            lbl_ComLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/iconappimg_small.png"))); // NOI18N
            lbl_ComLogo.setHorizontalAlignment(SwingConstants.CENTER);
        }

    }
}
