/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SUBUI;

import COMMONFUN.ComboColur;
import CONTROLLERS.C_UserGroup;
import MAIN.Frm_Main;
import MODELS.MPermissions;
import MODELS.MUsergroup;
import UI.Frm_Table;
import VALIDATIONS.MyValidator;
import WINMNG.MyWindowBasicControllers;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author HOME
 */
public class Frm_SUserGroupPer extends javax.swing.JInternalFrame implements MyWindowBasicControllers {

    Frm_Table ft = null;

    Frm_Main mainW = null;
    MyValidator fv = null;
    C_UserGroup cug = null;
    ComboColur com_render=null;
    public Frm_SUserGroupPer(Frm_Main mainw, String ScreenName) {
        initComponents();
        this.setTitle(ScreenName);
        this.lblScreenName.setText(ScreenName);
        this.mainW = mainw;
        this.fv = new MyValidator();
        this.cug = new C_UserGroup();
       // this.com_render=new ComboColur(cmb_Usergrp);
      // cmb_Usergrp.setRenderer(new ComboColur());
        
        Refresh();
        setShortCutKeys(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblScreenName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_Usergrp_Cur = new javax.swing.JComboBox<>();
        cmb_Usergrp = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        butNewUsergrp = new javax.swing.JButton();
        butEditUsergrp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree_sel_usergrp = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        tree_cur_usergrp = new javax.swing.JTree();
        butAddPer = new javax.swing.JButton();
        lblState = new javax.swing.JLabel();
        jpanelq = new javax.swing.JPanel();

        setClosable(true);
        setTitle("caption");
        setName(""); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lblScreenName.setBackground(new java.awt.Color(153, 255, 51));
        lblScreenName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblScreenName.setText("caption");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(670, 670, 670)
                .addComponent(lblScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblScreenName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel4.setText("Your User Group");

        cmb_Usergrp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_UsergrpItemStateChanged(evt);
            }
        });
        cmb_Usergrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_UsergrpActionPerformed(evt);
            }
        });

        jLabel5.setText("User Group");

        butNewUsergrp.setText("New +");
        butNewUsergrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNewUsergrpActionPerformed(evt);
            }
        });

        butEditUsergrp.setText("Edit");
        butEditUsergrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEditUsergrpActionPerformed(evt);
            }
        });

        tree_sel_usergrp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tree_sel_usergrpKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tree_sel_usergrp);

        jScrollPane2.setViewportView(tree_cur_usergrp);

        butAddPer.setText(">>");
        butAddPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddPerActionPerformed(evt);
            }
        });

        lblState.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(cmb_Usergrp_Cur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cmb_Usergrp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(butEditUsergrp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(butNewUsergrp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(butAddPer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Usergrp_Cur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Usergrp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butEditUsergrp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butNewUsergrp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(butAddPer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelq, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setBounds(0, 0, 862, 697);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

    }//GEN-LAST:event_formInternalFrameOpened

    private void butEditUsergrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEditUsergrpActionPerformed
        MUsergroup ug = (MUsergroup) cmb_Usergrp.getSelectedItem();
        if (ug != null) {
            Frm_Sub_UserGrp frm_ug = new Frm_Sub_UserGrp(mainW, true, ug);
            frm_ug.setVisible(true);
            Refresh();
        }


    }//GEN-LAST:event_butEditUsergrpActionPerformed

    private void butNewUsergrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNewUsergrpActionPerformed

        Frm_Sub_UserGrp frm_ug = new Frm_Sub_UserGrp(mainW, true, null);
        frm_ug.setVisible(true);
        Refresh();


    }//GEN-LAST:event_butNewUsergrpActionPerformed

    private void butAddPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddPerActionPerformed

        addPermissions();

    }//GEN-LAST:event_butAddPerActionPerformed

    private void tree_sel_usergrpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tree_sel_usergrpKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            MUsergroup ug = (MUsergroup) cmb_Usergrp.getSelectedItem();
            if (ug != null) {
                if (ug.getActive()==1) {
                    int state = JOptionPane.showConfirmDialog(rootPane, "Do you want to remove selected Permission?", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.YES_NO_OPTION);
                    if (state == JOptionPane.YES_OPTION) {
                        removeAssignedPer();
                    }
                } else {
                    lblState.setText("[DEACTIVE]");
                }
            }
        }


    }//GEN-LAST:event_tree_sel_usergrpKeyPressed

    private void cmb_UsergrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_UsergrpActionPerformed
    changePerm();

    }//GEN-LAST:event_cmb_UsergrpActionPerformed

    private void cmb_UsergrpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_UsergrpItemStateChanged
        changePerm();
    }//GEN-LAST:event_cmb_UsergrpItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAddPer;
    private javax.swing.JButton butEditUsergrp;
    private javax.swing.JButton butNewUsergrp;
    private javax.swing.JComboBox<String> cmb_Usergrp;
    private javax.swing.JComboBox<String> cmb_Usergrp_Cur;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanelq;
    private javax.swing.JLabel lblScreenName;
    private javax.swing.JLabel lblState;
    private javax.swing.JTree tree_cur_usergrp;
    private javax.swing.JTree tree_sel_usergrp;
    // End of variables declaration//GEN-END:variables

    @Override
    public void SaveProcess() {

    }

    @Override
    public void EditMode() {

    }

    @Override
    public void Refresh() {

        try {
            cmb_Usergrp.setModel(new DefaultComboBoxModel(cug.getUserGroups(true, true)));

            cmb_Usergrp_Cur.setModel(new DefaultComboBoxModel(cug.getUserGroups(false, false)));
            cmb_Usergrp_Cur.setEnabled(false);
            cmb_Usergrp_Cur.setSelectedItem(GLOBALDATA.GlobalData.CurUser.getMUsergroup());

            tree_cur_usergrp.setModel(null);

            tree_sel_usergrp.setModel(null);

            MUsergroup ugc = (MUsergroup) cmb_Usergrp_Cur.getSelectedItem();
            MUsergroup ug = (MUsergroup) cmb_Usergrp.getSelectedItem();
            createUserMenu(ugc.getId(), tree_cur_usergrp);
            if (ug != null) {
                if(ug.getActive()==0){
                   lblState.setText("[Deactive]");  
                }else{
                     lblState.setText("");
                }
               
                createUserMenu(ug.getId(), tree_sel_usergrp);
            }
            
         //   cmb_Usergrp.setRenderer(aRenderer);

        } catch (Exception ex) {
            Logger.getLogger(Frm_SUserGroupPer.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        }
    }

    public void setShortCutKeys(JInternalFrame f) {

        String exit = "exit";
        InputMap inputMap0 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap0.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), exit);
        ActionMap actionMap0 = f.getRootPane().getActionMap();
        actionMap0.put(exit, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                exit();
            }

        }
        );

        String Search = "Search";
        InputMap inputMap1 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap1.put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), Search);
        ActionMap actionMap1 = f.getRootPane().getActionMap();
        actionMap1.put(Search, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                SearchMode();
            }

        }
        );

        String Save = "Save";
        InputMap inputMap2 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap2.put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), Save);
        ActionMap actionMap2 = f.getRootPane().getActionMap();
        actionMap2.put(Save, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                SaveProcess();
            }

        }
        );

        String Edit = "Edit";
        InputMap inputMap3 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap3.put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), Edit);
        ActionMap actionMap3 = f.getRootPane().getActionMap();
        actionMap3.put(Edit, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                EditMode();
            }

        }
        );

        String Refresh = "Refresh";
        InputMap inputMap4 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap4.put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), Refresh);
        ActionMap actionMap4 = f.getRootPane().getActionMap();
        actionMap4.put(Refresh, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                Refresh();
            }

        }
        );

    }

    private void exit() {

        try {
            this.setClosed(true);
            mainW.CurrentFrame = "";

        } catch (PropertyVetoException ex) {
            Logger.getLogger(Frm_SUserGroupPer.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        }

    }

    @Override
    public void setDisableEnableComponents(JComponent[] EnComlist, JComponent[] DisComlist) {
        for (JComponent c : DisComlist) {
            c.setEnabled(false);
        }
        for (JComponent c : EnComlist) {
            c.setEnabled(true);
        }

    }

    @Override
    public void SearchMode() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void createUserMenu(int ugid, JTree tree) {
        Map<String, DefaultMutableTreeNode> NodesMap = new TreeMap<String, DefaultMutableTreeNode>();
        try {
            ArrayList<MPermissions> menus = cug.getUserGroupPermitions(ugid, 0);
            //create the root node
            DefaultMutableTreeNode root = new DefaultMutableTreeNode("");

            tree.setCellRenderer(new DefaultTreeCellRenderer() {
                private Icon loadIcon = UIManager.getIcon("OptionPane.errorIcon");
                // private Icon homeIcon = new ImageIcon(getClass().getResource("/SYSIMG/TreeIcons/home.png"));
                private Icon saveIcon = UIManager.getIcon("OptionPane.informationIcon");

                //private Icon loadIcon = new ImageIcon(getClass().getResource("/SYSIMG/iconappimg.png"));
                //private Icon saveIcon = new ImageIcon(getClass().getResource("/SYSIMG/iconappimg.png"));
                @Override
                public Component getTreeCellRendererComponent(JTree tree,
                        Object value, boolean selected, boolean expanded,
                        boolean isLeaf, int row, boolean focused) {
                    Component c = super.getTreeCellRendererComponent(tree, value,
                            selected, expanded, isLeaf, row, focused);

                    if (selected) {
                        if (value.toString().equals("Home")) {
                            //   setIcon(homeIcon);
                        }
                    } else if (value.toString().equals("Home")) {
                        //  setIcon(homeIcon);
                    }

                    return c;

                }
            });

            for (MPermissions p : menus) {
                //System.out.println(p.getId() + "-" + p.getParentid());

                if (p.getId().equals(p.getParentid())) {
                    if (NodesMap.get(p.getId()) == null) {
                        DefaultMutableTreeNode parent = new DefaultMutableTreeNode(p);
                        NodesMap.put(p.getId(), parent);
                        root.add(parent);

                    }
                } else {
                    DefaultMutableTreeNode parent = NodesMap.get(p.getParentid());
                    if (parent != null) {
                        DefaultMutableTreeNode node = new DefaultMutableTreeNode(p);
                        NodesMap.put(p.getId(), node);
                        parent.add(node);
                    }
                }
            }
            tree.setModel(new DefaultTreeModel(root));

        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }

    private void addPermissions() {
        try {
            MUsergroup ug = (MUsergroup) cmb_Usergrp.getSelectedItem();
            if (ug.getActive() == 1) {
                TreePath[] selectionPaths = tree_cur_usergrp.getSelectionPaths();
                //  System.out.println(selectionPath.getLastPathComponent());

                ArrayList<MPermissions> arper = new ArrayList<>();
                for (TreePath selectionPath : selectionPaths) {

                    DefaultMutableTreeNode mtn = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
                    MPermissions p = (MPermissions) mtn.getUserObject();
                    if (ug != null) {

                        arper.add(p);
                    }
                }
                cug.addBulkPermissions(ug.getId(), arper);
                createUserMenu(ug.getId(), tree_sel_usergrp);
            } else {
                JOptionPane.showMessageDialog(rootPane, "You can`t add or remove Permission from Deactived User group", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
                lblState.setText("[DEACTIVE]");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
        }

    }

    private void removeAssignedPer() {
        try {
            TreePath selectionPath = tree_sel_usergrp.getSelectionPath();
            //  System.out.println(selectionPath.getLastPathComponent());

            MUsergroup ug = (MUsergroup) cmb_Usergrp.getSelectedItem();
            DefaultMutableTreeNode mtn = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
            MPermissions p = (MPermissions) mtn.getUserObject();
            if (ug != null) {
                cug.RemovePermissionFromGroup(ug.getId(), p);
                createUserMenu(ug.getId(), tree_sel_usergrp);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
        }

    }

    private void changePerm() {
     MUsergroup ug = (MUsergroup) cmb_Usergrp.getSelectedItem();
            if (ug != null) {
                if (ug.getActive()==1) {
                    lblState.setText("");
                } else {
                    lblState.setText("[DEACTIVE]");
                }
                createUserMenu(ug.getId(), tree_sel_usergrp);
            }}

}
