/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SUBUI;

import CONTROLLERS.C_Units;

import MAIN.Frm_Main;
import MODELS.MUnitGroup;
import MODELS.MUnitGroupAssign;
import MODELS.MUnits;
import Test.Frm_Test;
import UI.Frm_Table;
import VALIDATIONS.MyValidator;
import WINMNG.MyWindowBasicControllers;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOME
 */
public class Frm_MUnitGroup extends javax.swing.JInternalFrame implements MyWindowBasicControllers {
    
    Frm_Table ft = null;
    
    Frm_Main mainW = null;
    MyValidator fv = null;
    
    C_Units c_units = null;
    
    public Frm_MUnitGroup(Frm_Main mainw, String ScreenName) {
        initComponents();
        c_units = new C_Units();
        this.setTitle(ScreenName);
        this.lblScreenName.setText(ScreenName);
        this.mainW = mainw;
        this.fv = new MyValidator();
        createLayOut();
        Refresh();
        setShortCutKeys(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layout_Parent = new javax.swing.JTabbedPane();
        layout_UnitGroup = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_UnitGroupId = new javax.swing.JTextField();
        txt_UnitGroupName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Chk_Active = new javax.swing.JCheckBox();
        layout_UnitGroupAssign = new javax.swing.JPanel();
        cmb_UAUnit = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txt_UAVolume = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUAList = new javax.swing.JTable();
        but_UnitGroup = new javax.swing.JButton();
        Chk_Activeuga = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        but_LocUpdate = new javax.swing.JButton();
        but_LocSave = new javax.swing.JButton();
        but_LocSearch = new javax.swing.JButton();
        butLocRefresh = new javax.swing.JButton();
        lblScreenName = new javax.swing.JLabel();
        jpanelq = new javax.swing.JPanel();

        setClosable(true);
        setTitle("caption");
        setName(""); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layout_UnitGroup.setBackground(new java.awt.Color(226, 226, 226));
        layout_UnitGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText("System will provide Auto Number for Code. So you need not to enter Code while creating  new Records");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        layout_UnitGroup.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 820, 40));

        txt_UnitGroupId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UnitGroupIdActionPerformed(evt);
            }
        });
        txt_UnitGroupId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UnitGroupIdKeyTyped(evt);
            }
        });
        layout_UnitGroup.add(txt_UnitGroupId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 150, 30));
        layout_UnitGroup.add(txt_UnitGroupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 260, 30));

        jLabel2.setText("Code");
        layout_UnitGroup.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, 30));

        jLabel4.setText("Description *");
        layout_UnitGroup.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 110, 30));

        Chk_Active.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chk_ActiveMouseClicked(evt);
            }
        });
        layout_UnitGroup.add(Chk_Active, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 180, -1));

        Layout_Parent.addTab("Unit Group Create", layout_UnitGroup);

        layout_UnitGroupAssign.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layout_UnitGroupAssign.add(cmb_UAUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 160, 30));

        jLabel1.setText("Volume");
        layout_UnitGroupAssign.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 160, -1));
        layout_UnitGroupAssign.add(txt_UAVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 160, 30));

        jLabel3.setText("Unit ");
        layout_UnitGroupAssign.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 160, -1));

        tblUAList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Unit", "Volume", "Base Unit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUAList);
        if (tblUAList.getColumnModel().getColumnCount() > 0) {
            tblUAList.getColumnModel().getColumn(0).setResizable(false);
            tblUAList.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblUAList.getColumnModel().getColumn(1).setResizable(false);
            tblUAList.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblUAList.getColumnModel().getColumn(2).setResizable(false);
            tblUAList.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        layout_UnitGroupAssign.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 790, 290));

        but_UnitGroup.setText("Add");
        but_UnitGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_UnitGroupActionPerformed(evt);
            }
        });
        layout_UnitGroupAssign.add(but_UnitGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 90, 30));

        Chk_Activeuga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Chk_ActiveugaMouseClicked(evt);
            }
        });
        layout_UnitGroupAssign.add(Chk_Activeuga, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 180, -1));

        Layout_Parent.addTab("Assign Units to Group", layout_UnitGroupAssign);

        getContentPane().add(Layout_Parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 860, 570));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        but_LocUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/Controlls/edit.png"))); // NOI18N
        but_LocUpdate.setToolTipText("Save");
        but_LocUpdate.setContentAreaFilled(false);
        but_LocUpdate.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/Controlls/edit_disable.png"))); // NOI18N
        but_LocUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_LocUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(but_LocUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 40, 40));

        but_LocSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/Controlls/Save.png"))); // NOI18N
        but_LocSave.setToolTipText("Save");
        but_LocSave.setContentAreaFilled(false);
        but_LocSave.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/Controlls/Save_disable.png"))); // NOI18N
        but_LocSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_LocSaveActionPerformed(evt);
            }
        });
        jPanel2.add(but_LocSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        but_LocSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/Controlls/Search.png"))); // NOI18N
        but_LocSearch.setToolTipText("Search(F2)");
        but_LocSearch.setContentAreaFilled(false);
        but_LocSearch.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/Controlls/Search_disable.png"))); // NOI18N
        but_LocSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_LocSearchActionPerformed(evt);
            }
        });
        jPanel2.add(but_LocSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 40, 40));

        butLocRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/Controlls/refresh.png"))); // NOI18N
        butLocRefresh.setToolTipText("Refresh");
        butLocRefresh.setContentAreaFilled(false);
        butLocRefresh.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/Controlls/refresh_disable.png"))); // NOI18N
        butLocRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLocRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(butLocRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 40, 40));

        lblScreenName.setBackground(new java.awt.Color(153, 255, 51));
        lblScreenName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblScreenName.setText("caption");
        jPanel2.add(lblScreenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 180, 40));
        jPanel2.add(jpanelq, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 270, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        setBounds(0, 0, 867, 646);
    }// </editor-fold>//GEN-END:initComponents

    private void but_LocSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_LocSearchActionPerformed
        SearchMode();
    }//GEN-LAST:event_but_LocSearchActionPerformed

    private void butLocRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLocRefreshActionPerformed
        Refresh();
    }//GEN-LAST:event_butLocRefreshActionPerformed

    private void but_LocSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_LocSaveActionPerformed
        SaveProcess();
    }//GEN-LAST:event_but_LocSaveActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

    }//GEN-LAST:event_formInternalFrameOpened

    private void but_LocUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_LocUpdateActionPerformed
EditMode();
    }//GEN-LAST:event_but_LocUpdateActionPerformed

    private void txt_UnitGroupIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UnitGroupIdActionPerformed
        loadUnitGroup();
    }//GEN-LAST:event_txt_UnitGroupIdActionPerformed

    private void txt_UnitGroupIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UnitGroupIdKeyTyped

    }//GEN-LAST:event_txt_UnitGroupIdKeyTyped

    private void Chk_ActiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chk_ActiveMouseClicked

    }//GEN-LAST:event_Chk_ActiveMouseClicked

    private void Chk_ActiveugaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Chk_ActiveugaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Chk_ActiveugaMouseClicked

    private void but_UnitGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_UnitGroupActionPerformed
        addUnit();
    }//GEN-LAST:event_but_UnitGroupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Chk_Active;
    private javax.swing.JCheckBox Chk_Activeuga;
    private javax.swing.JTabbedPane Layout_Parent;
    private javax.swing.JButton butLocRefresh;
    private javax.swing.JButton but_LocSave;
    private javax.swing.JButton but_LocSearch;
    private javax.swing.JButton but_LocUpdate;
    private javax.swing.JButton but_UnitGroup;
    private javax.swing.JComboBox cmb_UAUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelq;
    private javax.swing.JPanel layout_UnitGroup;
    private javax.swing.JPanel layout_UnitGroupAssign;
    private javax.swing.JLabel lblScreenName;
    private javax.swing.JTable tblUAList;
    private javax.swing.JTextField txt_UAVolume;
    private javax.swing.JTextField txt_UnitGroupId;
    private javax.swing.JTextField txt_UnitGroupName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void SaveProcess() {
        if (checkValidate()) {
            DefaultTableModel dtm = (DefaultTableModel) tblUAList.getModel();
            if (txt_UnitGroupId.getText().equals("")) {
                //new
                try {
                    MUnitGroup ug = new MUnitGroup();
                    ug.setUnitGroupId(c_units.GenerateNewUnitGroupNo());
                    ug.setUnitGroupName(txt_UnitGroupName.getText());
                    ug.setUnitGroupActive(Chk_Active.isSelected() ? 1 : 0);
                    
                    ArrayList<MUnitGroupAssign> uga = new ArrayList<>();
                    for (int i = 0; i < dtm.getRowCount(); i++) {
                        MUnits u = (MUnits) dtm.getValueAt(i, 0);
                        double volume = Double.parseDouble(dtm.getValueAt(i, 1).toString());
                        
                        boolean IsBase = Boolean.valueOf(dtm.getValueAt(i, 2).toString());
                        
                        uga.add(new MUnitGroupAssign(ug.getUnitGroupId(), u.getId(), volume, IsBase ? 1 : 0, 1));
                    }
                    c_units.SaveUnitGroup(ug, uga);
                    JOptionPane.showMessageDialog(rootPane, "Save Sucessfull", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.INFORMATION_MESSAGE);
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "ERROR :" + e.getMessage(), GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
                    
                }
            } else {
                String unitId = txt_UnitGroupId.getText();
                try {
                    MUnitGroup ug = c_units.findUnitGroupExists(unitId);
                    if (ug != null) {
                        
                        ug.setUnitGroupName(txt_UnitGroupName.getText());
                        ug.setUnitGroupActive(Chk_Active.isSelected() ? 1 : 0);
                        
                        ArrayList<MUnitGroupAssign> uga = new ArrayList<>();
                        for (int i = 0; i < dtm.getRowCount(); i++) {
                            MUnits u = (MUnits) dtm.getValueAt(i, 0);
                            double volume = Double.parseDouble(dtm.getValueAt(i, 1).toString());
                            boolean IsBase = Boolean.valueOf(dtm.getValueAt(i, 2).toString());
                            uga.add(new MUnitGroupAssign(ug.getUnitGroupId(), u.getId(), volume, IsBase ? 1 : 0, 1));
                        }
                        c_units.UpdateUnitGroup(ug, uga);
                        
                        JOptionPane.showMessageDialog(rootPane, "Update Sucessfull", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.INFORMATION_MESSAGE);
                        
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Couldn`t find specific Unit group for :" + unitId, GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
                        
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "ERROR :" + e.getMessage(), GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }
    }
    
    @Override
    public void EditMode() {
         JComponent[] DisComlist={but_LocSearch};
                      JComponent[] EnComlist={but_LocSave,txt_UnitGroupId,txt_UnitGroupName,Chk_Active,tblUAList,txt_UAVolume,Chk_Activeuga};      
                    setDisableEnableComponents(EnComlist, DisComlist); 
    }
    
    @Override
    public void Refresh() {
        txt_UnitGroupId.setText("");
        txt_UnitGroupName.setText("");
        DefaultTableModel dtm = (DefaultTableModel) tblUAList.getModel();
        
        dtm.setRowCount(0);
        txt_UAVolume.setText("");
        Chk_Active.setSelected(true);
        Chk_Activeuga.setSelected(true);
        txt_UnitGroupId.grabFocus();
    }
    
    public void setShortCutKeys(JInternalFrame f) {
        
        String exit = "exit";
        InputMap inputMap0 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap0.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), exit);
        ActionMap actionMap0 = f.getRootPane().getActionMap();
        actionMap0.put(exit, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                exit();
            }

        }
        );

        String Search = "Search";
        InputMap inputMap1 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap1.put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), Search);
        ActionMap actionMap1 = f.getRootPane().getActionMap();
        actionMap1.put(Search, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                SearchMode();
            }

        }
        );
        
          String Save = "Save";
        InputMap inputMap2 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap2.put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), Save);
        ActionMap actionMap2 = f.getRootPane().getActionMap();
        actionMap2.put(Save, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                SaveProcess();
            }

        }
        );
        
           String Edit = "Edit";
        InputMap inputMap3 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap3.put(KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0), Edit);
        ActionMap actionMap3 = f.getRootPane().getActionMap();
        actionMap3.put(Edit, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                EditMode();
            }

        }
        );
        
          String Refresh = "Refresh";
        InputMap inputMap4 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap4.put(KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0), Refresh);
        ActionMap actionMap4 = f.getRootPane().getActionMap();
        actionMap4.put(Refresh, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                Refresh();
            }

        }
        );

    }
    
    private void exit() {
        
        try {
            this.setClosed(true);
            mainW.CurrentFrame = "";
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Frm_MUnitGroup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    @Override
    public void setDisableEnableComponents(JComponent[] EnComlist, JComponent[] DisComlist) {
        for (JComponent c : DisComlist) {
            c.setEnabled(false);
        }
        for (JComponent c : EnComlist) {
            c.setEnabled(true);
        }
        
    }
    
    @Override
    public void SearchMode() {
        Vector<String> col = new Vector<>();
        col.add("Code");
        col.add("Des");
        
        String[] SQL_Col = {"ID", "NAME"};
        String SQL = "select ID,NAME from M_UNITGROUPS ";
        
        Connection currentCon = null;
        try {
            currentCon = DB_Access.DB.getCurrentCon();
        } catch (Exception ex) {
            Logger.getLogger(Frm_Test.class.getName()).log(Level.SEVERE, null, ex);
        }        
        if (ft == null) {
            
            ft = new Frm_Table(txt_UnitGroupId, currentCon, col, SQL_Col, SQL, "");
            ft.setVisible(true);
            
        } else {
            ft = null;
            ft = new Frm_Table(txt_UnitGroupId, currentCon, col, SQL_Col, SQL, "");
            ft.setFocusable(true);
            ft.setVisible(true);
        }
        
    }
    
    private boolean checkValidate() {
        boolean state = true;
        
        if (txt_UnitGroupName.getText().equals("")) {
            state = false;
            JOptionPane.showMessageDialog(rootPane, "Please provide Unit group Name", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
        } else if (tblUAList.getRowCount() == 0) {
            state = false;
            Layout_Parent.setSelectedIndex(1);
            JOptionPane.showMessageDialog(rootPane, "Please assign units to this group", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
            
        }
        return state;
    }
    
    private void createLayOut() {
        Vector<MUnits> v = c_units.getAllUnits();
        cmb_UAUnit.setModel(new DefaultComboBoxModel(v));
    }
    
    private void addUnit() {
        if (validateUnitAssign()) {
            MUnits u = (MUnits) cmb_UAUnit.getSelectedItem();
            
            DefaultTableModel dtm = (DefaultTableModel) tblUAList.getModel();
            
            String BaseUnit = "";
            for (int i = 0; i < dtm.getRowCount(); i++) {
                MUnits ug = (MUnits) dtm.getValueAt(i, 0);
                // double vol = Double.parseDouble(dtm.getValueAt(i, 1).toString());
                Boolean IsBase = Boolean.getBoolean(dtm.getValueAt(i, 2).toString());
                if (IsBase) {
                    BaseUnit = ug.getId();
                }
                if (u.getId().equals(ug.getId())) {
                    dtm.removeRow(i);
                    
                }
            }
            
            Vector v = new Vector();
            v.add(u);
            v.add(txt_UAVolume.getText());
            if (BaseUnit.equals("")) {
                v.add(Chk_Activeuga.isSelected());
            } else {
                v.add(false);
            }
            dtm.addRow(v);
            
        }
    }
    
    private boolean validateUnitAssign() {
        boolean state = true;
        
        if (cmb_UAUnit.getItemCount() == 0) {
            state = false;
            JOptionPane.showMessageDialog(rootPane, "No units found!", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
            
        } else if (txt_UAVolume.getText().equals("")) {
            state = false;
            JOptionPane.showMessageDialog(rootPane, "Please add volume", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
            
        }
        
        return state;
        
    }
    
    private void loadUnitGroup() {
        String Unitgroup = txt_UnitGroupId.getText();
        if (!Unitgroup.equals("")) {
            try {
                MUnitGroup ug = c_units.findUnitGroupExists(Unitgroup);
                if (ug != null) {
                    txt_UnitGroupName.setText(ug.getUnitGroupName());
                    Chk_Active.setSelected(ug.getUnitGroupActive() == 1 ? true : false);
                    
                    ArrayList<Vector> ar = c_units.getAllAssignUnits(ug.getUnitGroupId());
                    DefaultTableModel dtm = (DefaultTableModel) tblUAList.getModel();
                    dtm.setRowCount(0);
                    for (Vector v : ar) {
                        dtm.addRow(v);
                    }
                    JComponent[] EnComlist={txt_UnitGroupId};
                      JComponent[] DisComlist={but_LocSave,txt_UnitGroupName,Chk_Active,tblUAList,txt_UAVolume,Chk_Activeuga};      
                    setDisableEnableComponents(EnComlist, DisComlist);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "This Unit group no is not exists", GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
                    
                }
            } catch (Exception e) {
            }
            
        } else {
            txt_UnitGroupName.grabFocus();
        }
    }
    
}
