package MODELS;
// Generated Jun 12, 2016 10:23:46 AM by Hibernate Tools 3.6.0

/**
 * MGroup1 generated by hbm2java
 */
public class MGroupCommon  {


     private String id;
     private String name;
     private byte active;

    public MGroupCommon() {
    }

    public MGroupCommon(String id, String name, byte active) {
        this.id = id;
        this.name = name;
        this.active = active;
    }

     
    public byte getActive() {
        return active;
    }

    public void setActive(byte active) {
        this.active = active;
    }

  
    
	
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return this.name;
    }

    @Override
    public boolean equals(Object obj) {
        MGroupCommon gc=(MGroupCommon) obj;
        if(gc.id.equals(this.id)){
            return true;
        }else{
            return false;
        }
    }

  
    
    

    
}


