package MODELS;
// Generated Jun 12, 2016 10:23:46 AM by Hibernate Tools 3.6.0

import DB_Access.DB;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * MLocation generated by hbm2java
 */
public class MLocation implements java.io.Serializable {

    private Integer id;
    private String name;
    private Byte active;
    private Byte visible;
    private String refno;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Byte getActive() {
        return this.active;
    }

    public void setActive(Byte active) {
        this.active = active;
    }

    public Byte getVisible() {
        return this.visible;
    }

    public void setVisible(Byte visible) {
        this.visible = visible;
    }

    public String getRefno() {
        return this.refno;
    }

    public void setRefno(String refno) {
        this.refno = refno;
    }

    @Override
    public String toString() {
        return this.name;
    }
    

    
}
