package MODELS;
// Generated Jun 12, 2016 10:23:46 AM by Hibernate Tools 3.6.0

/**
 * MPaydet generated by hbm2java
 */
public class MPaydet  implements java.io.Serializable {


     private String id;
     private String mstId;
     private String name;
     private Double rate;
    private String shortname;
     private int order;
private Byte active;
   private Byte refreq;
   private Byte datef;
   
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getRate() {
        return this.rate;
    }
    
    public void setRate(Double rate) {
        this.rate = rate;
    }

    public String getShortname() {
        return shortname;
    }

    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    public int getOrder() {
        return order;
    }

    public void setOrder(int order) {
        this.order = order;
    }

    public Byte getActive() {
        return active;
    }

    public void setActive(Byte active) {
        this.active = active;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMstId() {
        return mstId;
    }

    public void setMstId(String mstId) {
        this.mstId = mstId;
    }

    public Byte getRefreq() {
        return refreq;
    }

    public void setRefreq(Byte refreq) {
        this.refreq = refreq;
    }
   

   @Override
    public String toString() {
        String name="";
        
        if(getShortname()==null || getShortname().equals("")){
            if(getName()!=null){
            name=getName();
            }
        }else{
            name=getShortname();
        }
        
        return name;
    }

  @Override
    public boolean equals(Object obj) {
        MPaydet mst=(MPaydet)obj;
        if(mst.getId().equals(getId())){
            return true;
        }else{
            return false;
        }
        
    }

    public Byte getDatef() {
        return datef;
    }

    public void setDatef(Byte datef) {
        this.datef = datef;
    }
}


