package MODELS;
// Generated Jun 12, 2016 10:23:46 AM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * MProducts generated by hbm2java
 */
public class MProducts implements java.io.Serializable {

    private String id;
    private String parentid;
    private String MGroup3;
    private String MGroup4;
    private String MGroup2;
    private String MGroup1;
    private String MUserByMduser;
    private String MGroup5;
    private String MUserByCruser;
    private String name;
    private String printdes;
    private Byte active;
    private Byte batch;
    private Double markup;
    private Double sprice;
    private Double cprice;
    private Date crdate;
    private Date mddate;
    private String ref1;
    private String ref2;
    private String UnitGroupId;
    private String proImg;
    private Double commision;

    public MProducts() {
    }

    public MProducts(String id, String parentid, String MGroup3, String MGroup4, String MGroup2, String MGroup1, String MUserByMduser, String MGroup5, String MUserByCruser, String name, String printdes, Byte active, Byte batch, Double markup, Double sprice, Double cprice, Date crdate, Date mddate, String ref1, String ref2, String UnitGroupId, String proImg,Double com) {
        this.id = id;
        this.parentid = parentid;
        this.MGroup3 = MGroup3;
        this.MGroup4 = MGroup4;
        this.MGroup2 = MGroup2;
        this.MGroup1 = MGroup1;
        this.MUserByMduser = MUserByMduser;
        this.MGroup5 = MGroup5;
        this.MUserByCruser = MUserByCruser;
        this.name = name;
        this.printdes = printdes;
        this.active = active;
        this.batch = batch;
        this.markup = markup;
        this.sprice = sprice;
        this.cprice = cprice;
        this.crdate = crdate;
        this.mddate = mddate;
        this.ref1 = ref1;
        this.ref2 = ref2;
        this.UnitGroupId = UnitGroupId;
        this.proImg = proImg;
        this.commision=com;
    }

    public Double getMarkup() {
        return markup;
    }

    public void setMarkup(Double markup) {
        this.markup = markup;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMGroup3() {
        return MGroup3;
    }

    public void setMGroup3(String MGroup3) {
        this.MGroup3 = MGroup3;
    }

    public String getMGroup4() {
        return MGroup4;
    }

    public void setMGroup4(String MGroup4) {
        this.MGroup4 = MGroup4;
    }

    public String getMGroup2() {
        return MGroup2;
    }

    public void setMGroup2(String MGroup2) {
        this.MGroup2 = MGroup2;
    }

    public String getMGroup1() {
        return MGroup1;
    }

    public void setMGroup1(String MGroup1) {
        this.MGroup1 = MGroup1;
    }

    public String getMUserByMduser() {
        return MUserByMduser;
    }

    public void setMUserByMduser(String MUserByMduser) {
        this.MUserByMduser = MUserByMduser;
    }

    public String getMGroup5() {
        return MGroup5;
    }

    public void setMGroup5(String MGroup5) {
        this.MGroup5 = MGroup5;
    }

    public String getMUserByCruser() {
        return MUserByCruser;
    }

    public void setMUserByCruser(String MUserByCruser) {
        this.MUserByCruser = MUserByCruser;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrintdes() {
        return printdes;
    }

    public void setPrintdes(String printdes) {
        this.printdes = printdes;
    }

    public Byte getActive() {
        return active;
    }

    public void setActive(Byte active) {
        this.active = active;
    }

    public Byte getBatch() {
        return batch;
    }

    public void setBatch(Byte batch) {
        this.batch = batch;
    }

    public Double getSprice() {
        return sprice;
    }

    public void setSprice(Double sprice) {
        this.sprice = sprice;
    }

    public Double getCprice() {
        return cprice;
    }

    public void setCprice(Double cprice) {
        this.cprice = cprice;
    }

    public Date getCrdate() {
        return crdate;
    }

    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }

    public Date getMddate() {
        return mddate;
    }

    public void setMddate(Date mddate) {
        this.mddate = mddate;
    }

    public String getRef1() {
        return ref1;
    }

    public void setRef1(String ref1) {
        this.ref1 = ref1;
    }

    public String getRef2() {
        return ref2;
    }

    public void setRef2(String ref2) {
        this.ref2 = ref2;
    }

    public String getUnitGroupId() {
        return UnitGroupId;
    }

    public void setUnitGroupId(String UnitGroupId) {
        this.UnitGroupId = UnitGroupId;
    }

    public String getProImg() {
        return proImg;
    }

    public void setProImg(String proImg) {
        this.proImg = proImg;
    }

    public String getParentid() {
        return parentid;
    }

    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    public Double getCommision() {
        return commision;
    }

    public void setCommision(Double commision) {
        this.commision = commision;
    }

}
