package MODELS;
// Generated Jun 12, 2016 10:23:46 AM by Hibernate Tools 3.6.0

import DB_Access.DB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;

/**
 * MUsergroup generated by hbm2java
 */
public class MUsergroup implements java.io.Serializable {

    private Integer id;
    private String groupname;
    private Byte active;
    private Byte visible;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGroupname() {
        return this.groupname;
    }

    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    public Byte getActive() {
        return this.active;
    }

    public void setActive(Byte active) {
        this.active = active;
    }

    public Byte getVisible() {
        return this.visible;
    }

    public void setVisible(Byte visible) {
        this.visible = visible;
    }

    
}
