package MODELS;
// Generated Jun 12, 2016 10:23:46 AM by Hibernate Tools 3.6.0

/**
 * TPhystkdet generated by hbm2java
 */
public class TPhystkdet implements java.io.Serializable {

    private TPhystkmst TPhystkmst;
    private Double sysqty;
    private MUnits MUnitSys;
    private Double phyqty;
    private MUnits MUnits;
    private String proid;
    private MUnitGroup MUnitGrp;
    private String Batch;

    public TPhystkdet() {
    }

    public MUnits getMUnits() {
        return this.MUnits;
    }

    public void setMUnits(MUnits MUnits) {
        this.MUnits = MUnits;
    }

    public TPhystkmst getTPhystkmst() {
        return this.TPhystkmst;
    }

    public void setTPhystkmst(TPhystkmst TPhystkmst) {
        this.TPhystkmst = TPhystkmst;
    }

    public Double getSysqty() {
        return this.sysqty;
    }

    public void setSysqty(Double sysqty) {
        this.sysqty = sysqty;
    }

    public Double getPhyqty() {
        return this.phyqty;
    }

    public void setPhyqty(Double phyqty) {
        this.phyqty = phyqty;
    }

    public MUnitGroup getMUnitGrp() {
        return MUnitGrp;
    }

    public void setMUnitGrp(MUnitGroup MUnitGrp) {
        this.MUnitGrp = MUnitGrp;
    }

    public String getBatch() {
        return Batch;
    }

    public void setBatch(String Batch) {
        this.Batch = Batch;
    }

    public MUnits getMUnitSys() {
        return MUnitSys;
    }

    public void setMUnitSys(MUnits MUnitSys) {
        this.MUnitSys = MUnitSys;
    }

    public String getProid() {
        return proid;
    }

    public void setProid(String proid) {
        this.proid = proid;
    }

}
