package MODELS;
// Generated Jun 12, 2016 10:23:46 AM by Hibernate Tools 3.6.0



/**
 * UCusreports generated by hbm2java
 */
public class UCusreports  implements java.io.Serializable {


     private String id;
     private String displayname;
     private String repname;
     private Byte customer;
     private Byte supplier;
     private Byte daterange;

    public UCusreports() {
    }

	
    public UCusreports(String id) {
        this.id = id;
    }
    public UCusreports(String id, String displayname, String repname, Byte customer, Byte supplier, Byte daterange) {
       this.id = id;
       this.displayname = displayname;
       this.repname = repname;
       this.customer = customer;
       this.supplier = supplier;
       this.daterange = daterange;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getDisplayname() {
        return this.displayname;
    }
    
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }
    public String getRepname() {
        return this.repname;
    }
    
    public void setRepname(String repname) {
        this.repname = repname;
    }
    public Byte getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Byte customer) {
        this.customer = customer;
    }
    public Byte getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Byte supplier) {
        this.supplier = supplier;
    }
    public Byte getDaterange() {
        return this.daterange;
    }
    
    public void setDaterange(Byte daterange) {
        this.daterange = daterange;
    }




}


