package MODELS;
// Generated Jun 12, 2016 10:23:46 AM by Hibernate Tools 3.6.0



/**
 * UReports generated by hbm2java
 */
public class UReports  implements java.io.Serializable {


     private String perno;
     private String displayname;
     private String rptname;

    public UReports() {
    }

	
    public UReports(String perno) {
        this.perno = perno;
    }
    public UReports(String perno, String displayname, String rptname) {
       this.perno = perno;
       this.displayname = displayname;
       this.rptname = rptname;
    }
   
    public String getPerno() {
        return this.perno;
    }
    
    public void setPerno(String perno) {
        this.perno = perno;
    }
    public String getDisplayname() {
        return this.displayname;
    }
    
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }
    public String getRptname() {
        return this.rptname;
    }
    
    public void setRptname(String rptname) {
        this.rptname = rptname;
    }




}


