package MODELS;
// Generated Jun 12, 2016 10:23:46 AM by Hibernate Tools 3.6.0



/**
 * UserPermitionsId generated by hbm2java
 */
public class UserPermitionsId  implements java.io.Serializable {


     private int MUsergroupId;
     private String MPermissionsId;
     private String MPermissionsParentid;

    public UserPermitionsId() {
    }

    public UserPermitionsId(int MUsergroupId, String MPermissionsId, String MPermissionsParentid) {
       this.MUsergroupId = MUsergroupId;
       this.MPermissionsId = MPermissionsId;
       this.MPermissionsParentid = MPermissionsParentid;
    }
   
    public int getMUsergroupId() {
        return this.MUsergroupId;
    }
    
    public void setMUsergroupId(int MUsergroupId) {
        this.MUsergroupId = MUsergroupId;
    }
    public String getMPermissionsId() {
        return this.MPermissionsId;
    }
    
    public void setMPermissionsId(String MPermissionsId) {
        this.MPermissionsId = MPermissionsId;
    }
    public String getMPermissionsParentid() {
        return this.MPermissionsParentid;
    }
    
    public void setMPermissionsParentid(String MPermissionsParentid) {
        this.MPermissionsParentid = MPermissionsParentid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserPermitionsId) ) return false;
		 UserPermitionsId castOther = ( UserPermitionsId ) other; 
         
		 return (this.getMUsergroupId()==castOther.getMUsergroupId())
 && ( (this.getMPermissionsId()==castOther.getMPermissionsId()) || ( this.getMPermissionsId()!=null && castOther.getMPermissionsId()!=null && this.getMPermissionsId().equals(castOther.getMPermissionsId()) ) )
 && ( (this.getMPermissionsParentid()==castOther.getMPermissionsParentid()) || ( this.getMPermissionsParentid()!=null && castOther.getMPermissionsParentid()!=null && this.getMPermissionsParentid().equals(castOther.getMPermissionsParentid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMUsergroupId();
         result = 37 * result + ( getMPermissionsId() == null ? 0 : this.getMPermissionsId().hashCode() );
         result = 37 * result + ( getMPermissionsParentid() == null ? 0 : this.getMPermissionsParentid().hashCode() );
         return result;
   }   


}


