/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MAIN;

import COMMONFUN.JTreeMenuCellRender;
import GLOBALDATA.GlobalData;
import LOGIN.Frm_Login;
import MODELS.MPermissions;
import MODELS.MUsergroup;
import SUBUI.Frm_Help;
import WINMNG.MyWindowManager;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.apache.poi.util.IOUtils;

/**
 *
 * @author HOME
 */
public class Frm_Main extends javax.swing.JFrame {

    public String CurrentFrame = "";

    Frm_Login frmlog = null;
    MUsergroup ug = null;
    ArrayList<MPermissions> menus = null;
    MyWindowManager myw = null;
    Frm_Help frm_Help = null;

    public Frm_Main() {
        initComponents();
        this.setUndecorated(true);
    }

    public Frm_Main(Frm_Login frmlogin, ArrayList<MPermissions> m) {
        initComponents();
        this.frmlog = frmlogin;
        this.menus = m;
        this.ug = new MUsergroup();
        this.myw = new MyWindowManager();
        this.lblUsername.setText(GlobalData.CurUser.getFirstname());
        this.lblCompanyName.setText(GlobalData.Setup.getComname());
        this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        this.frm_Help = new Frm_Help(this, true);
        this.txt_DB_HOST.setText("Server:  " + GlobalData.config.getServer());
        this.txt_DB_Name.setText("DB:  " + GlobalData.config.getDb());
        RefreshLayOut();
        createUserMenu();
        setShortCutKeys(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layout_Outer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TUserMenu = new javax.swing.JTree();
        JDesktopF = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_Global_Instructions = new javax.swing.JLabel();
        butLogout = new javax.swing.JButton();
        lblCompanyName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblUserimg = new javax.swing.JLabel();
        txt_DB_Name = new javax.swing.JLabel();
        txt_DB_HOST = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        layout_Outer.setBackground(new java.awt.Color(255, 255, 255));
        layout_Outer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        layout_Outer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        TUserMenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        TUserMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TUserMenuMouseClicked(evt);
            }
        });
        TUserMenu.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                TUserMenuValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(TUserMenu);

        layout_Outer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, 550));

        JDesktopF.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/iconappimg.png"))); // NOI18N
        JDesktopF.add(jLabel3);
        jLabel3.setBounds(330, 180, 220, 110);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("ERP");
        JDesktopF.add(jLabel5);
        jLabel5.setBounds(450, 290, 100, 44);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Biz");
        JDesktopF.add(jLabel6);
        jLabel6.setBounds(380, 280, 80, 58);

        layout_Outer.add(JDesktopF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 868, 630));

        lbl_Global_Instructions.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbl_Global_Instructions.setForeground(new java.awt.Color(204, 0, 0));
        lbl_Global_Instructions.setText("[  F2 : SEARCH   ]   [   F3: EDIT  ]  [  F4: REFRESH  ]   [  F5: SAVE  ]  [F6: HOLD]  [F7: CANCEL]");
        layout_Outer.add(lbl_Global_Instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 670, 750, -1));

        butLogout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butLogout.setForeground(new java.awt.Color(89, 143, 179));
        butLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/if_free-09_463017.png"))); // NOI18N
        butLogout.setToolTipText("Exit [Esc]");
        butLogout.setBorderPainted(false);
        butLogout.setContentAreaFilled(false);
        butLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLogoutActionPerformed(evt);
            }
        });
        layout_Outer.add(butLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 0, 40, 30));

        lblCompanyName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCompanyName.setForeground(new java.awt.Color(102, 102, 102));
        lblCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompanyName.setText("COMPANY NAME");
        layout_Outer.add(lblCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 760, 30));

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(102, 102, 102));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("BUWANEKA");
        layout_Outer.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 150, 30));

        lblUserimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/1465731972_user-01.png"))); // NOI18N
        layout_Outer.add(lblUserimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 100, 80));

        txt_DB_Name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_DB_Name.setForeground(new java.awt.Color(102, 102, 102));
        txt_DB_Name.setText("jLabel1");
        layout_Outer.add(txt_DB_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 700, 200, -1));

        txt_DB_HOST.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_DB_HOST.setForeground(new java.awt.Color(102, 102, 102));
        txt_DB_HOST.setText("jLabel1");
        layout_Outer.add(txt_DB_HOST, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 190, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/if_question_2625632.png"))); // NOI18N
        jButton1.setToolTipText("Help [F1] ");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        layout_Outer.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 30));

        getContentPane().add(layout_Outer, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 1030, 720));

        setSize(new java.awt.Dimension(1035, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TUserMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TUserMenuMouseClicked
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) TUserMenu.getLastSelectedPathComponent();

        if (node != null && node.isLeaf()) {
            try {
                openWindow((MPermissions) node.getUserObject());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Couldn`t open window: " + ex.getMessage(), GLOBALDATA.GlobalData.MESSAGEBOX, JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_TUserMenuMouseClicked

    private void TUserMenuValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_TUserMenuValueChanged

    }//GEN-LAST:event_TUserMenuValueChanged

    private void butLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLogoutActionPerformed
        Logout();
    }//GEN-LAST:event_butLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ShowHelp();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {

        /* try {
         UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
         } catch (ClassNotFoundException ex) {
         Logger.getLogger(Frm_Login.class.getName()).log(Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
         Logger.getLogger(Frm_Login.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
         Logger.getLogger(Frm_Login.class.getName()).log(Level.SEVERE, null, ex);
         } catch (UnsupportedLookAndFeelException ex) {
         Logger.getLogger(Frm_Login.class.getName()).log(Level.SEVERE, null, ex);
         }
         */
        //frm.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane JDesktopF;
    private javax.swing.JTree TUserMenu;
    private javax.swing.JButton butLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel layout_Outer;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblUserimg;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbl_Global_Instructions;
    private javax.swing.JLabel txt_DB_HOST;
    private javax.swing.JLabel txt_DB_Name;
    // End of variables declaration//GEN-END:variables

    public void setShortCutKeys(JFrame f) {

        String exit = "exit";
        InputMap inputMap0 = f.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap0.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), exit);
        ActionMap actionMap0 = f.getRootPane().getActionMap();
        actionMap0.put(exit, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                Logout();
            }

        }
        );

      

      

    }
    
    
    
    private void createUserMenu() {
        TreeMap<String, DefaultMutableTreeNode> NodesMap = new TreeMap<String, DefaultMutableTreeNode>();
        try {

            //create the root node
            DefaultMutableTreeNode root = new DefaultMutableTreeNode("");

            for (MPermissions p : menus) {
                //  System.out.println(p.getId() + "-" + p.getParentid());

                if (p.getId().equals(p.getParentid())) {
                    if (NodesMap.get(p.getId()) == null) {
                        DefaultMutableTreeNode parent = new DefaultMutableTreeNode(p);
                        NodesMap.put(p.getId(), parent);
                        root.add(parent);

                    }
                } else {
                    DefaultMutableTreeNode parent = NodesMap.get(p.getParentid());
                    if (parent != null) {
                        DefaultMutableTreeNode node = new DefaultMutableTreeNode(p);
                        NodesMap.put(p.getId(), node);
                        parent.add(node);
                    }

                }
            }
            TUserMenu.setModel(new DefaultTreeModel(root));
            TUserMenu.setCellRenderer(new JTreeMenuCellRender());
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }

    private void openWindow(MPermissions p) throws Exception {

        JInternalFrame jf = myw.getRequestWindow(p, this);
        if (jf != null) {
            jf.setFocusCycleRoot(true);
            jf.setMaximizable(false);
            jf.setClosable(false);
            ((javax.swing.plaf.basic.BasicInternalFrameUI) jf.getUI()).setNorthPane(null);
            jf.setBorder(null);
            jf.setBounds(0, 0, 868, 630);
            jf.addInternalFrameListener(new InternalFrameListener() {

                //[110,147,169]
                @Override
                public void internalFrameOpened(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameClosing(InternalFrameEvent e) {
                    CurrentFrame = "";
                }

                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    CurrentFrame = "";
                }

                @Override
                public void internalFrameIconified(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameDeiconified(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameActivated(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameDeactivated(InternalFrameEvent e) {
                }
            });

            if (CurrentFrame.equals(p.getId())) {
                jf.setSelected(true);

                jf.setFocusable(true);
                jf.moveToFront();
            } else {
                CurrentFrame = p.getId();
                JDesktopF.removeAll();
                JDesktopF.updateUI();

                JDesktopF.add(jf);

                jf.setVisible(true);

                jf.setFocusable(true);
                jf.setSelected(true);
                jf.moveToFront();
            }

        }

    }

    private void RefreshLayOut() {
        String imgpath = GlobalData.CurUser.getImgurl();
        File f = new File(imgpath);
        if (f.exists()) {
            BufferedImage img = null;
            try {
                img = ImageIO.read(f);
                Image dimg = img.getScaledInstance(70, 70,
                        Image.SCALE_SMOOTH);

                lblUserimg.setIcon(new ImageIcon(dimg));
            } catch (IOException e) {
                e.printStackTrace();
            }

        } else if (GlobalData.CurUser.getId().equals("U0000")) {
            BufferedImage img = null;
            try {
                img = ImageIO.read(getClass().getResource("/SYSIMG/ADMIN.jpg"));
                Image dimg = img.getScaledInstance(70, 70,
                        Image.SCALE_SMOOTH);
                lblUserimg.setIcon(new ImageIcon(dimg)); // NOI18N
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            lblUserimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SYSIMG/1465731972_user-01.png"))); // NOI18N
        }

    }

    private void Logout() {
        int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Do you want to logout from the System", GlobalData.MESSAGEBOX, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (showConfirmDialog == JOptionPane.YES_OPTION) {
            Frm_Login l = new Frm_Login();
            this.dispose();
            l.setVisible(true);
        }

    }

    private void ShowHelp() {

        frm_Help.setVisible(true);
    }

}
